# Generated by Django 6.1 on 2026-08-10 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CodingChallenge',
            fields=[
                ('challenge_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('hint', models.TextField(blank=True, null=True)),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('learning_status', models.CharField(blank=True, max_length=50, null=True)),
                ('example_of_correct_code', models.TextField(blank=True, null=True)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'db_table': 'coding_challenges',
                'indexes': [models.Index(fields=['difficulty'], name='idx_challenges_difficulty'), models.Index(fields=['learning_status'], name='idx_challenges_learning_status')],
            },
        ),
        migrations.CreateModel(
            name='AiQuestion',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to='core.codingchallenge')),
            ],
            options={
                'db_table': 'ai_questions',
                'indexes': [models.Index(fields=['user'], name='idx_ai_questions_user_id'), models.Index(fields=['challenge'], name='idx_ai_questions_challenge_id')],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submit', models.TextField()),
                ('submit_status', models.CharField(max_length=50)),
                ('passed_testcases', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.codingchallenge')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'results',
                'indexes': [models.Index(fields=['user'], name='idx_results_user_id'), models.Index(fields=['challenge'], name='idx_results_challenge_id'), models.Index(fields=['timestamp'], name='idx_results_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('testcase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.codingchallenge')),
            ],
            options={
                'db_table': 'test_cases',
                'indexes': [models.Index(fields=['challenge'], name='idx_test_cases_challenge_id')],
            },
        ),
        migrations.CreateModel(
            name='UserCompletedChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='completed_by_users', to='core.codingchallenge')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='completed_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_completed_challenges',
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge'), name='pk_user_completed_challenges')],
            },
        ),
    ]
