# Generated by Django 6.1 on 2026-08-13 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_testcase_input_alter_testcase_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAssessment',
            fields=[
                ('assessment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending - questions generated, awaiting answers'), ('IN_PROGRESS', 'User answering questions'), ('COMPLETED', 'Assessment completed')], default='PENDING', max_length=20)),
                ('questions', models.JSONField()),
                ('answers', models.JSONField(blank=True, null=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('detailed_scores', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_assessment', to='core.result')),
            ],
            options={
                'db_table': 'code_assessments',
                'indexes': [models.Index(fields=['result'], name='idx_assessments_result_id'), models.Index(fields=['status'], name='idx_assessments_status')],
            },
        ),
    ]
