# Generated by Django 6.1 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_codeassessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("Avatar01.png", "Avatar 01"),
                    ("Avatar02.png", "Avatar 02"),
                    ("Avatar03.png", "Avatar 03"),
                    ("Avatar04.png", "Avatar 04"),
                    ("Avatar05.png", "Avatar 05"),
                    ("Avatar06.png", "Avatar 06"),
                ],
                default="Avatar01.png",
                max_length=32,
            ),
        ),
    ]
